### ISSUE TITLE
Functor extensionality?

### ISSUE THREAD

**Issue by clayrat** [ahmadsalim/desc-n-crunch#3]
@anton-trunov suggested that we could try extending the definition of `VerifiedFunctor` with a claim weaker than functional extensionality:

> functorExtensionality : (x : f a) -> ((z : a) -> d1 z = d2 z) -> map d1 x = map d2 x

Not sure if this would be enough to prove the rest of laws though.

**Comment by anton-trunov** [comment]
I actually didn't try it, but if we don't define `VerifiedFunctor` for (wrapped) functions, then I guess we can try to do without the axiom of functional extensionality.

**Comment by ahmadsalim** [comment]
Thanks for the suggestion.
To be honest, I don't really mind functional extensionality as postulate now, but if you find it preferrable you are welcome to add it after everything else is finished. Note however you want something like:
```idris
functorExtensionality : ((z : a) -> d1 z = d2 z) -> map d1 = map d2
```

I am not sure whether this allows us to prove the basic law of `map id = id` however.

**Comment by ahmadsalim** [comment]
Thinking a bit more about it, we do unfortunately need full funext.

**Comment by clayrat** [comment]
@ahmadsalim Care to elaborate?

**Comment by ahmadsalim** [comment]
@clayrat The suggested law is simply too weak to prove either mapId or mapComp.

I.e., it requires a `map` on both sides to be applicable, but `map id = id` and `map (f . g) = map f . map g` does not have that shape.
